version: 2.1
orbs:
  cypress: cypress-io/cypress@1.20.0
executors:
  mac:
    macos:
      xcode: 10.1.0
workflows:
  build_and_test:
    jobs:
      - cypress/install:
          build: "npm run build"
      - cypress/run:
          name: Test on Chrome 73
          requires:
            - cypress/install
          executor: "cypress/browsers-chrome73-ff68"
          browser: chrome
          start: "npm run serve"
          wait-on: "http://localhost:8080"
          record: true
          store_artifacts: true
      - cypress/run:
          name: Test on Firefox 68
          requires:
            - cypress/install
          executor: "cypress/browsers-chrome73-ff68"
          browser: firefox
          start: "npm run serve"
          wait-on: "http://localhost:8080"
          record: true
          store_artifacts: true
      - cypress/run:
          name: Test on Mac
          requires:
            - cypress/install
          executor: "mac"
          start: "npm run serve"
          wait-on: "http://localhost:8080"
          record: true
          store_artifacts: true

